### ISSUE TITLE
Card Deck Support? 

### ISSUE THREAD

**Issue by C0ffeeGoblin** [radimous/VaultCuriosEnhancements#3]
Amazing mod, thank you so much!

In a similar fashion to how you added the Shard Pouch, are you able to add the Card Deck?

Thanks again!

**Comment by radimous** [comment]
??
deck has curio in vanilla, it just doesn't have tooltip because they haven't added the tag
you can use this datapack to add the tag 
[deck_curio_datapack.zip](https://github.com/user-attachments/files/16644022/deck_curio_datapack.zip)
